### ISSUE TITLE
Diseño de diagrama #1

### ISSUE THREAD

**Issue by emiliohernandezdev** [UMGMascotasAntigua/Documentacion#1]

**Comment by wmong3f** [comment]
![Diagrama de red](https://github.com/UMGMascotasAntigua/Documentacion/assets/168782820/2b59dc96-325f-4ec4-9941-da3de3628486)
![Diagrama de red](https://github.com/UMGMascotasAntigua/Documentacion/assets/168782820/75689daa-6a56-48c8-b935-d0d47ceb46a9)
