### ISSUE TITLE
Manual de Usuario

### ISSUE THREAD

**Issue by wmong3f** [UMGMascotasAntigua/Documentacion#18]

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/df0fb047-e485-471a-acce-8c30fea70307)
Pantalla principal

**Comment by emiliohernandezdev** [comment]
Barra de navegación:
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/f5f83b22-f1c0-41cb-947c-dd2cda735ce3)

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/f1d5800d-95c7-4ddb-bd18-97eb58c43845)
Crear mascota

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/cd68ddfd-4a79-43fe-a1eb-828a85205864)
Listado de mascotas (Modo Administrador)

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/094cf44e-7d65-4c74-be33-055363b840e3)
Listado de mascotas modo administrador

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/35436d6f-30e2-4eca-8e90-2cf2a9ebe10e)
Búsqueda de mascotas (filtro)

**Comment by emiliohernandezdev** [comment]
Editar mascota
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/c26a9868-9e55-48a2-acc8-e4505ca53afa)

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/a10eb60a-83a5-4a44-920a-3cd3dd54732f)
Crear vacuna (tipo) solo admins

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/7690711b-17c1-4b4a-8c35-9401eb05f640)
Vacunar (solo admins)

**Comment by emiliohernandezdev** [comment]
![image](https://github.com/UMGMascotasAntigua/Documentacion/assets/30883223/d8cd086f-fa54-4213-bb30-1ed0f3b36f5b)
Anuncios
