### ISSUE TITLE
Diseño de diagrama #2

### ISSUE THREAD

**Issue by emiliohernandezdev** [UMGMascotasAntigua/Documentacion#2]

**Comment by MIGUELDXD** [comment]
![Image](https://github.com/UMGMascotasAntigua/Documentacion/assets/145181768/76ceacf2-58cc-40db-b0ca-18dd461762c2)

**Comment by MIGUELDXD** [comment]
![Image](https://github.com/UMGMascotasAntigua/Documentacion/assets/145181768/9d09e54a-891f-4996-a7b5-fb30eddc254f)
