### ISSUE TITLE
Ruta crítica del Sistema

### ISSUE THREAD

**Issue by emiliohernandezdev** [UMGMascotasAntigua/Documentacion#3]
@wmong3f crear ruta critica

**Comment by wmong3f** [comment]
![Tabla](https://github.com/UMGMascotasAntigua/Documentacion/assets/168782820/6c636de6-4326-4ebd-9fb9-954a25fedefa)

**Comment by wmong3f** [comment]
![Ruta Critica](https://github.com/UMGMascotasAntigua/Documentacion/assets/168782820/bd1873f4-b591-4c7b-bc1f-70565f9d4843)
